#!/bin/sh /etc/rc.common

START=95
STOP=50

EXTRA_COMMANDS="force"
EXTRA_HELP="    force   force refresh"

start() {
        update6 &
}

stop() {
	update6 stop
}


force() {
        update6 force &
}
